version: "3.8"
services:
  db:
    container_name: postgresAph
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=audioPhile
      - POSTGRES_HOST=localhost
  server:
#    environment:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - bucketName=${bucketName}
      - database=${POSTGRES_DB}
      - host=db
      - password=${POSTGRES_PASSWORD}
      - port=${port}
      - secretKey=${secretKey}
      - serviceKey=${serviceKey}
      - user=${user}
    links:
      - db
    ports:
      - "8080:8080"