version: "3.8"
services:
  db:
    container_name: postgresAph
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=audioPhile
      - POSTGRES_HOST=localhost
    env_file:
      - .env
  server:
    container_name: golang
    image: ${imageName}
    ports:
      - "8080:8080"
    environment:
      - bucketName=${bucketName}
      - database=${POSTGRES_DB}
      - host=172.18.0.2
      - password=${POSTGRES_PASSWORD}
      - port=${port}
      - secretKey=${secretKey}
      - serviceKey=${serviceKey}
      - user=${user}
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    external_links:
      - db